//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.225
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThetisCore.Task.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThetisCore.Task.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon activated {
            get {
                object obj = ResourceManager.GetObject("activated", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon AppIcon {
            get {
                object obj = ResourceManager.GetObject("AppIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Cannot confirm valid License-Key. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_CANNOT_CONFIRM_VALID_LIC_KEY {
            get {
                return ResourceManager.GetString("ERR_CANNOT_CONFIRM_VALID_LIC_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to activate Zeptair VPN Service. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_FAILED_TO_ACTIVATE_SVC {
            get {
                return ResourceManager.GetString("ERR_FAILED_TO_ACTIVATE_SVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to disable Zeptair VPN Service. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_FAILED_TO_DISABLE_SVC {
            get {
                return ResourceManager.GetString("ERR_FAILED_TO_DISABLE_SVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Authentication Failed. Please confirm your User Name and Password. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_ON_START_AUTH_FAILED {
            get {
                return ResourceManager.GetString("ERR_ON_START_AUTH_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid License-Key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_ON_START_LICKEY {
            get {
                return ResourceManager.GetString("ERR_ON_START_LICKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The process already exists. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_PROCESS_EXISTS {
            get {
                return ResourceManager.GetString("ERR_PROCESS_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;Zeptair VPN Connect&apos; has been canceled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_ZEPT_SVC_START_CANCELED {
            get {
                return ResourceManager.GetString("ERR_ZEPT_SVC_START_CANCELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_EXIT {
            get {
                return ResourceManager.GetString("MENU_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Navi Panel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_NAVI_PANEL {
            get {
                return ResourceManager.GetString("MENU_NAVI_PANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RSS Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_RSS_SETTINGS {
            get {
                return ResourceManager.GetString("MENU_RSS_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Thetis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_THETIS_BROWSER {
            get {
                return ResourceManager.GetString("MENU_THETIS_BROWSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Zeptair Web に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_ZEPT_BROWSER {
            get {
                return ResourceManager.GetString("MENU_ZEPT_BROWSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zeptair VPN Connect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_ZEPT_CONNECT {
            get {
                return ResourceManager.GetString("MENU_ZEPT_CONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zeptair VPN Disconnect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_ZEPT_DISCONNECT {
            get {
                return ResourceManager.GetString("MENU_ZEPT_DISCONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zeptair Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_ZEPT_SETTINGS {
            get {
                return ResourceManager.GetString("MENU_ZEPT_SETTINGS", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon standby {
            get {
                object obj = ResourceManager.GetObject("standby", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   ACTIVATED に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STATUS_ACTIVATED {
            get {
                return ResourceManager.GetString("STATUS_ACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auth. FAILED に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STATUS_AUTH_FAILED {
            get {
                return ResourceManager.GetString("STATUS_AUTH_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DISABLED に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string STATUS_DISABLED {
            get {
                return ResourceManager.GetString("STATUS_DISABLED", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon unavailable {
            get {
                object obj = ResourceManager.GetObject("unavailable", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon undefined {
            get {
                object obj = ResourceManager.GetObject("undefined", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Execute Now に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZEPTCMD_CONFIRM_EXEC_NOW {
            get {
                return ResourceManager.GetString("ZEPTCMD_CONFIRM_EXEC_NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   in 10 min. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZEPTCMD_CONFIRM_IN_10MIN {
            get {
                return ResourceManager.GetString("ZEPTCMD_CONFIRM_IN_10MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   in 1 hour に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZEPTCMD_CONFIRM_IN_1H {
            get {
                return ResourceManager.GetString("ZEPTCMD_CONFIRM_IN_1H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   in 5 hours に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZEPTCMD_CONFIRM_IN_5H {
            get {
                return ResourceManager.GetString("ZEPTCMD_CONFIRM_IN_5H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Confirmation later に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZEPTCMD_CONFIRM_LATER {
            get {
                return ResourceManager.GetString("ZEPTCMD_CONFIRM_LATER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ThetisCore is about to execute commands requested from Thetis. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZEPTCMD_CONFIRM_MSG {
            get {
                return ResourceManager.GetString("ZEPTCMD_CONFIRM_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tomorrow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZEPTCMD_CONFIRM_TOMORROW {
            get {
                return ResourceManager.GetString("ZEPTCMD_CONFIRM_TOMORROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Executing commands has been finished. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZEPTCMD_DONE {
            get {
                return ResourceManager.GetString("ZEPTCMD_DONE", resourceCulture);
            }
        }
    }
}
