//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThetisCore.Conf.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThetisCore.Conf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ADD {
            get {
                return ResourceManager.GetString("ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string APPLY {
            get {
                return ResourceManager.GetString("APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap arrow_right_lightpink {
            get {
                object obj = ResourceManager.GetObject("arrow_right_lightpink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap arrow_right_pink {
            get {
                object obj = ResourceManager.GetObject("arrow_right_pink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Authentication に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AUTHENTICATION {
            get {
                return ResourceManager.GetString("AUTHENTICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap ball_blue {
            get {
                object obj = ResourceManager.GetObject("ball_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap close_off {
            get {
                object obj = ResourceManager.GetObject("close_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap config {
            get {
                object obj = ResourceManager.GetObject("config", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Adopt the following words as title? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CONFIRM_ADOPT_AS_TITLE {
            get {
                return ResourceManager.GetString("CONFIRM_ADOPT_AS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All items in  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CONFIRM_COMPLETELY_ALL_DELETE_1 {
            get {
                return ResourceManager.GetString("CONFIRM_COMPLETELY_ALL_DELETE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    will be completely deleted. Are you sure? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CONFIRM_COMPLETELY_ALL_DELETE_2 {
            get {
                return ResourceManager.GetString("CONFIRM_COMPLETELY_ALL_DELETE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    will be completely deleted. Are you sure? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CONFIRM_COMPLETELY_DELETE {
            get {
                return ResourceManager.GetString("CONFIRM_COMPLETELY_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    will be deleted. Are you sure? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CONFIRM_DELETE {
            get {
                return ResourceManager.GetString("CONFIRM_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All items in  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CONFIRM_RESTORE_ALL_TRASH_1 {
            get {
                return ResourceManager.GetString("CONFIRM_RESTORE_ALL_TRASH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    will be restored to Navi Panel. Are you sure? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CONFIRM_RESTORE_ALL_TRASH_2 {
            get {
                return ResourceManager.GetString("CONFIRM_RESTORE_ALL_TRASH_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    will be restored to Navi Panel. Are you sure? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CONFIRM_RESTORE_TRASH {
            get {
                return ResourceManager.GetString("CONFIRM_RESTORE_TRASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection Result : OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CONNECTION_RESULT_OK {
            get {
                return ResourceManager.GetString("CONNECTION_RESULT_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EDIT {
            get {
                return ResourceManager.GetString("EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot connect to the specified URL. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERROR_CANNOT_CONNECT {
            get {
                return ResourceManager.GetString("ERROR_CANNOT_CONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please specify valid polling interval. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERROR_INVAID_INTERVAL {
            get {
                return ResourceManager.GetString("ERROR_INVAID_INTERVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap feed_icon {
            get {
                object obj = ResourceManager.GetObject("feed_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap file {
            get {
                object obj = ResourceManager.GetObject("file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   General Config. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GENERAL_CONFIG {
            get {
                return ResourceManager.GetString("GENERAL_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max. items to display : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MAX_ITEMS_TO_DISPLAY {
            get {
                return ResourceManager.GetString("MAX_ITEMS_TO_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Navi Panel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NAVI_PANEL {
            get {
                return ResourceManager.GetString("NAVI_PANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Polling Interval (min.) : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string POLLING_INTERVAL {
            get {
                return ResourceManager.GetString("POLLING_INTERVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restore に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RESTORE {
            get {
                return ResourceManager.GetString("RESTORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RSS Site に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RSS_SITE {
            get {
                return ResourceManager.GetString("RSS_SITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RSS Sites に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RSS_SITES {
            get {
                return ResourceManager.GetString("RSS_SITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RSS_TITLE {
            get {
                return ResourceManager.GetString("RSS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RSS URL : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RSS_URL {
            get {
                return ResourceManager.GetString("RSS_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please specify Title of this setting. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SPECIFY_SETTINGS_TITLE {
            get {
                return ResourceManager.GetString("SPECIFY_SETTINGS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please specify URL. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SPECIFY_URL {
            get {
                return ResourceManager.GetString("SPECIFY_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please specify User Name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SPECIFY_USER_NAME {
            get {
                return ResourceManager.GetString("SPECIFY_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Testing the specified URL ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string STATUS_TESTING_URL {
            get {
                return ResourceManager.GetString("STATUS_TESTING_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ThetisCore Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TITLE {
            get {
                return ResourceManager.GetString("TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Title already exists. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TITLE_EXISTS {
            get {
                return ResourceManager.GetString("TITLE_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trash に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TRASH {
            get {
                return ResourceManager.GetString("TRASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Name : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string USER_NAME {
            get {
                return ResourceManager.GetString("USER_NAME", resourceCulture);
            }
        }
    }
}
